[package]
name = "book-meta"
version = "0.1.0"
edition = "2024"

[features]
default = ["hardcover", "openlibrary", "googlebooks"]
hardcover = ["_provider"]
openlibrary = ["_provider"]
googlebooks = ["_provider"]

_provider = []

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["std", "serde", "clock"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
